language: php
dist: trusty

php:
- '5.4'
- '5.5'
- '5.6'
- '7.0'
- '7.1'
- '7.2'

before_script:
- if find . -name "*.php" -exec php -l {} 2>&1 \; | grep -iv "no syntax errors detected"; then exit 1; fi

script: true

install: true

notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
    - developers@cacti.net
  slack:
    secure: eJC5AbAnQi4VHS94mkVcmWRQLD4en28YzEMtKJG7toXw4NpFRNZkLP5cDxB8zTE04mcmsRn1NRonA6ZnsSuZ+ZIYiJBBsC4dvpIXoyf7O0OCXZAeU6iAGc4vO/VvnUnUfcTTTLaxyWHCQdwjlDFPxrQy6o9stNPkGiaehrxUtsK/j2woyjPxbM9Ucgn8cODeIyfS/gcIbGEZVmTorAajNjwDQg9mO102ooTXSbDmwM89I7U9CnoSZtRfRQsOnKEtb2qp+ZVQckc+UmMqq3VqPOdwCbQswNPqbCHzNY7yhJpT6EkAiT/TiCLGzh+ezXrfpX9ax2Fkb0OOcmpuyLzU7Bcpll7U5dnVEbzhhdRIvTWIaJ+Hi392CBp2IWTjdJmaNKrJUIGOCyyCcYv4m2ohMKqiOyOpMDDtjmu2o6fOYl3zN3kd27daIVHSnD612OPo4wQcGYmUPbDkyC64Gwb2oRoSDvaAOIeUoGlcWUYFNhRhkkLPlcgVeJf8eno9Wg7/hwacWIBnb/iFBwxCUAe4Ys05b0m3fTgUJVA8CNP1bFJMh1iQ/fpgJF3ocLgPGkNCSJIWobJ63/mGybuZHxY7Hz446svZm9ZG6rwOsyGXj40oXv2VDhB9FFDbhWj6Hw7jf2tgPkJ+7BCPg0waY6o4j1Djnmdm33CKMUDfKnH3Uj8=
